plugins {
    id 'com.android.application'
}

android {
    namespace 'com.redmi9aspeedboost'
    compileSdk 35

    defaultConfig {
        applicationId "com.redmi9aspeedboost"
        minSdk 29
        targetSdk 29
        versionCode 2
        versionName "1.2"
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
}
