plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '2.0.21'
}

android {
    namespace 'com.redmi9aspeedboost'
    compileSdk 35

    defaultConfig {
        applicationId "com.redmi9aspeedboost"
        minSdk 29
        targetSdk 29
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'app/src/main/AndroidManifest.xml'
            java.srcDirs = ['app/src/main/app/src/main/java']
            res.srcDirs = ['app/src/main/app/src/main/res']
        }
    }
}
