plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '2.0.21'
}

android {
    namespace 'com.redmi9aspeedboost'
    compileSdk 35

    defaultConfig {
        applicationId "com.redmi9aspeedboost"
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName "2.0.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main {
            manifest.srcFile 'app/app/src/main/AndroidManifest.xml'
            java.srcDirs = ['app/app/src/main/app/src/main/java']
            res.srcDirs = ['app/app/src/main/res']
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
